name = "api"
main = "./src/index.ts"
compatibility_date = "2023-02-01"
node_compat = true
account_id = "ca7ebe24ef9d607c47250ff8416651a1"
[[ d1_databases ]]
binding = "DB"
database_name = "jakspeedruns-fork-db"
database_id = "b03ebff1-cb9b-41de-b784-117a396969e4"
